server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8899/realms/DemoKeycloakMFA
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

keycloack:
  url-login: http://localhost:8899/realms/DemoKeycloakMFA/protocol/openid-connect/token
  grant-type: password
  client-id: mfaclient

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - health
          - metrics
